Feat: Alterar ícone app Bem-estar
practice-uffs/app-sae pull request #58
Opened 2022-03-08 12:23 UTC by GuilhermeGraeff

Ficou assim as alterações:

![222222222](https://user-images.githubusercontent.com/48657331/157237199-59b7c82b-9214-4ecb-a370-a0df97e0bfc2.gif)

fix: #57

2022-03-08 13:02 UTC, alissonpeloso commented
As PRs não precisa adicionar no projeto geral, nem a label "need-review". Adiciona só na issue :D

2022-03-08 13:03 UTC, alissonpeloso commented
Lembra de linkar a issue na PR sempre aqui:
![image](https://user-images.githubusercontent.com/51202705/157243365-a668c733-933f-4248-a967-d36101a2291a.png)

2022-03-08 13:19 UTC, alissonpeloso requested changes
@GuilhermeGraeff, tem um bug estranho. Ao entrar na página do app com a logo certa, se você atualiza a página ela volta com a logo do practice. Não sei se isso acontece no `apk`, teria que dar uma olhada

2022-03-09 10:55 UTC, GuilhermeGraeff commented
Aqui na minha máquina isto não está ocorrendo, vou arrumar o ambiente para conseguir gerar o apk e realizar mais testes então.
:)

2022-09-22 18:27 UTC, closed without merging