Chores: Pequenos ajustes e melhorias.
practice-uffs/app-sae pull request #85
Opened 2022-06-02 01:59 UTC by SWE3T

Vários ajustes e melhorias.

Fix #84

2022-06-03 10:54 UTC, alissonpeloso commented
- Pra mim a barrinha do diário com o negrito, itálico, etc. não funciona direito. Não tem como saber se tá selecionado uma das opções ou não. Eu cliquei várias vezes e só depois de algumas tentativas ele colocou em negrito.
- No calendário, no mês de maio fala que respondi o questionário de bem-estar, não sei se tá como dado estático ou algo assim.
- Acho que no calendário também precisaria de um indicativo de qual dia é hoje, pra facilitar.

2022-06-05 00:11 UTC, SWE3T commented
> Pra mim a barrinha do diário com o negrito, itálico, etc. não funciona direito. Não tem como saber se tá selecionado uma das opções ou não. Eu cliquei várias vezes e só depois de algumas tentativas ele colocou em negrito.

Para essa funcionalidade, primeiro o usuário precisa selecionar o texto e depois apertar o botão do efeito que deseja aplicar, no meu ele funciona direito, mas concordo que não é muito intuitivo. Vou verificar se não encontro alguma alternativa. 
 
<br>

> No calendário, no mês de maio fala que respondi o questionário de bem-estar, não sei se tá como dado estático ou algo assim.

Sim, tem uma implementação estática em um dia de maio que era para testes, vou retirar. 


<br>
Quanto em relação ao dia atual, é uma feature que já havia sido implementada mas aparentemente parou de funcionar :p 
@alissonpeloso

2022-06-06 13:59 UTC, alissonpeloso commented
@SWE3T, saquei. Você vai tentar fazer essas alterações nessa pr mesmo? ou quer que eu dê merge e depois você ajusta/melhora em outra issue?

2022-06-06 14:00 UTC, SWE3T commented
@alissonpeloso estou trabalhando em cima delas por esse pr mesmo

2022-06-17 12:08 UTC, alissonpeloso requested changes

2022-06-17 12:08 UTC, alissonpeloso commented on src/pages/track-menu.f7.html
>                  <a href="/wellness-quiz/" class="menu-grid__item">
```suggestion
                <a href="#" class="menu-grid__item">
```

Se você clica aqui, mesmo estando no grayscale ele direciona pra notfound. Se deixar sem o link fica melhor.

2022-06-18 18:38 UTC, merged